<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527101644 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shared.activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(20) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_760C0EACA76ED395 ON shared.activity_log (user_id)');
        $this->addSql('CREATE INDEX idx_activity_user_date ON shared.activity_log (user_id, occurred_at)');
        $this->addSql('ALTER TABLE shared.activity_log ADD CONSTRAINT FK_760C0EACA76ED395 FOREIGN KEY (user_id) REFERENCES shared.users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE shared.activity_log DROP CONSTRAINT FK_760C0EACA76ED395');
        $this->addSql('DROP TABLE shared.activity_log');
    }
}
