<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Garanties : stockage des documents constructeur (PDF) + liaison aux dossiers.
 *
 * Cas pilote : recapitulatif des avis de credit/debit OPEL telecharge par le
 * robot. Le robot uploade le PDF via l'API (POST /api/garanties/documents/upload)
 * sous une reference unique, et ecrit cette meme reference dans une colonne
 * « document » du Google Sheet (plusieurs references separees par « ; »). La
 * sync lit cette colonne et cree les liens dossier <-> document.
 *
 * Modele :
 *   - garanties.document : 1 ligne par PDF (metadonnees + binaire bytea),
 *     cle metier = reference (UNIQUE), idempotent au re-upload.
 *   - garanties.dossier_document : table de liaison N:N (un PDF couvre
 *     plusieurs DG, une DG peut figurer dans plusieurs PDF), cle = la reference.
 *
 * Choix volontaire : PAS de FK dossier_document.reference -> document.reference.
 * Le lien peut exister avant que le PDF ne soit uploade (la sync hebdo et
 * l'upload du robot arrivent dans un ordre quelconque). Le rapprochement se
 * fait par egalite de reference : si le PDF n'est pas encore la, la DG n'affiche
 * simplement pas de document, et ca se repare seul au prochain upload.
 *
 * Binaire en bytea (reste 100% sur Render). Acces encapsule derriere
 * DocumentStockageInterface pour pouvoir basculer vers un stockage objet
 * (R2/Backblaze) plus tard sans toucher au reste.
 */
final class Version20260623140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Garanties : tables document (PDF constructeur) et dossier_document (liaison N:N par reference)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE garanties.document ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            // Reference unique choisie par le robot (ex. opel-DL20911-1037301).
            // Sert de cle de liaison avec garanties.dossier_document.
            .'reference VARCHAR(255) NOT NULL, '
            .'marque VARCHAR(100) DEFAULT NULL, '
            .'type_document VARCHAR(64) DEFAULT NULL, '
            // Login/compte source (ex. account_key du portail constructeur) : tracabilite.
            .'compte_login VARCHAR(100) DEFAULT NULL, '
            .'concession VARCHAR(255) DEFAULT NULL, '
            // Periode couverte par le recap (semaine telechargee par le robot).
            .'periode_debut DATE DEFAULT NULL, '
            .'periode_fin DATE DEFAULT NULL, '
            .'nom_fichier VARCHAR(255) DEFAULT NULL, '
            .'mime VARCHAR(100) DEFAULT NULL, '
            .'taille INTEGER DEFAULT NULL, '
            .'hash_sha256 VARCHAR(64) DEFAULT NULL, '
            // Binaire du PDF. NULL tant que le contenu n'est pas (re)ecrit.
            .'contenu BYTEA DEFAULT NULL, '
            .'source VARCHAR(64) DEFAULT NULL, '
            .'importe_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_document_reference ON garanties.document (reference)');

        $this->addSql(
            'CREATE TABLE garanties.dossier_document ('
            .'dossier_id BIGINT NOT NULL, '
            .'reference VARCHAR(255) NOT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (dossier_id, reference))',
        );
        // Jointure depuis le document vers ses dossiers (et inversement).
        $this->addSql('CREATE INDEX idx_dossier_document_reference ON garanties.dossier_document (reference)');
        // Le lien disparait si le dossier est supprime (rare : historique conserve).
        $this->addSql(
            'ALTER TABLE garanties.dossier_document '
            .'ADD CONSTRAINT fk_dossier_document_dossier FOREIGN KEY (dossier_id) '
            .'REFERENCES garanties.dossier (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE garanties.dossier_document');
        $this->addSql('DROP TABLE garanties.document');
    }
}
