<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Recouvrement : moteur de règles de relance CONFIGURABLE.
 *
 * Crée recouvrement.regle_relance (la stratégie devient de la donnée, pilotée
 * depuis la vue Stratégies) et sème les deux règles "Standard" de départ :
 *   - Standard VN  : collectifs 4111000 + 4161000, 1re relance à 30j puis /15j, MED 90j.
 *   - Standard APV : collectifs 4114000 + 4164000, 1re relance à 15j puis /15j, MED 90j.
 * Filtre montant : montant_initial > 0 (colonne actuelle ; passera à
 * "montant_initial_facturation" lors de l'élargissement de v_impayes).
 *
 * Ne touche PAS v_impayes ni la sélection existante : ce moteur est branché sur
 * la sélection dans une étape ultérieure (élargissement de la vue + bascule).
 */
final class Version20260713120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recouvrement : table regle_relance (moteur configurable) + seed Standard VN/APV';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE recouvrement.regle_relance (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nom VARCHAR(120) NOT NULL,
                actif BOOLEAN NOT NULL DEFAULT TRUE,
                priorite INT NOT NULL DEFAULT 0,
                filtres JSON NOT NULL DEFAULT '[]',
                delai_initial SMALLINT NOT NULL DEFAULT 30,
                intervalle SMALLINT NOT NULL DEFAULT 15,
                seuil_med SMALLINT NOT NULL DEFAULT 90,
                continuer_apres_med BOOLEAN NOT NULL DEFAULT TRUE,
                releve_seul BOOLEAN NOT NULL DEFAULT FALSE,
                cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                modifie_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
            )
            SQL);
        $this->addSql('CREATE INDEX idx_regle_actif_priorite ON recouvrement.regle_relance (actif, priorite)');

        $this->addSql(<<<'SQL'
            INSERT INTO recouvrement.regle_relance
                (nom, actif, priorite, filtres, delai_initial, intervalle, seuil_med, continuer_apres_med, releve_seul, cree_le)
            VALUES
                ('Standard VN', TRUE, 10,
                 '[{"champ":"collectif","operateur":"in","valeur":["4111000","4161000"]},{"champ":"montant_initial","operateur":"gt","valeur":0}]',
                 30, 15, 90, TRUE, FALSE, NOW()),
                ('Standard APV', TRUE, 20,
                 '[{"champ":"collectif","operateur":"in","valeur":["4114000","4164000"]},{"champ":"montant_initial","operateur":"gt","valeur":0}]',
                 15, 15, 90, TRUE, FALSE, NOW())
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE recouvrement.regle_relance');
    }
}
