<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Module Recouvrement — strategies de relance.
 *
 * Une `strategie` est un scenario nomme (ex: "Strategie standard B2B") qui
 * decrit la suite des actions de relance. Chaque `strategie_niveau` est une
 * etape avec un delai (jours depuis l'echeance), un type d'action et,
 * eventuellement plus tard, un modele de courrier (FK ajoutee en phase 7).
 *
 * Un compte peut etre affecte a une seule strategie via `compte_strategie`,
 * qui porte aussi l'etat courant (a relancer, en cours, desactive,
 * repositionne, erreur) et la date de la prochaine relance prevue.
 */
final class Version20260528191502 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recouvrement : tables strategie, strategie_niveau et compte_strategie';
    }

    public function up(Schema $schema): void
    {
        // ----- creances.strategie ------------------------------------------
        $this->addSql(
            'CREATE TABLE creances.strategie ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'code VARCHAR(50) NOT NULL, '
            .'libelle VARCHAR(255) NOT NULL, '
            .'description TEXT DEFAULT NULL, '
            .'active BOOLEAN NOT NULL DEFAULT TRUE, '
            .'auteur_id INT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_creances_strategie_code ON creances.strategie (code)');
        $this->addSql('CREATE INDEX idx_creances_strategie_active ON creances.strategie (active)');
        $this->addSql(
            'ALTER TABLE creances.strategie ADD CONSTRAINT fk_creances_strategie_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // ----- creances.strategie_niveau ----------------------------------
        $this->addSql(
            'CREATE TABLE creances.strategie_niveau ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'strategie_id BIGINT NOT NULL, '
            .'ordre INT NOT NULL, '
            .'libelle VARCHAR(255) NOT NULL, '
            // jours_delai : 0 = jour de l'echeance, 7 = J+7, -3 = pre-relance
            .'jours_delai INT NOT NULL DEFAULT 0, '
            // type_action : telephone, email, courrier, sms, visite, autre
            .'type_action VARCHAR(30) NOT NULL, '
            // Pointer (logique) vers creances.modele_courrier (FK ajoutee en phase 7).
            .'modele_courrier_id BIGINT DEFAULT NULL, '
            .'condition_libelle VARCHAR(255) DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_sn_strategie ON creances.strategie_niveau (strategie_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_creances_sn_ordre ON creances.strategie_niveau (strategie_id, ordre)');
        $this->addSql(
            'ALTER TABLE creances.strategie_niveau ADD CONSTRAINT fk_creances_sn_strategie '
            .'FOREIGN KEY (strategie_id) REFERENCES creances.strategie (id) ON DELETE CASCADE',
        );

        // ----- creances.compte_strategie ----------------------------------
        $this->addSql(
            'CREATE TABLE creances.compte_strategie ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'compte_code VARCHAR(50) NOT NULL, '
            .'strategie_id BIGINT DEFAULT NULL, '
            // etat : a_relancer, cours, desactive, repositionne, erreur, fin
            .'etat VARCHAR(20) NOT NULL DEFAULT \'a_relancer\', '
            .'repositionne_jusqu_au DATE DEFAULT NULL, '
            .'date_derniere_relance TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'niveau_courant INT NOT NULL DEFAULT 0, '
            .'erreur_message TEXT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_creances_cs_compte ON creances.compte_strategie (compte_code)');
        $this->addSql('CREATE INDEX idx_creances_cs_strategie ON creances.compte_strategie (strategie_id)');
        $this->addSql('CREATE INDEX idx_creances_cs_etat ON creances.compte_strategie (etat)');
        $this->addSql(
            'ALTER TABLE creances.compte_strategie ADD CONSTRAINT fk_creances_cs_strategie '
            .'FOREIGN KEY (strategie_id) REFERENCES creances.strategie (id) ON DELETE SET NULL',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE creances.compte_strategie');
        $this->addSql('DROP TABLE creances.strategie_niveau');
        $this->addSql('DROP TABLE creances.strategie');
    }
}
