<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Recouvrement : gel de relance au niveau FACTURE (Phase 1 du chantier « relance au
 * site »). Table `recouvrement.facture_site` : une facture (ecriture_id) transferee
 * au site ou mise en pause. Tant que `actif`, la facture est exclue de la relance
 * client. Voir docs/RECOUVREMENT_RELANCE_SITE.md.
 */
final class Version20260806130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recouvrement : table facture_site (gel de relance au niveau facture)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE recouvrement.facture_site ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'ecriture_id VARCHAR(64) NOT NULL, '
            .'compte_code VARCHAR(64) NOT NULL, '
            .'code_site VARCHAR(8) DEFAULT NULL, '
            .'type VARCHAR(20) NOT NULL, '
            .'actif BOOLEAN NOT NULL, '
            .'montant NUMERIC(14, 2) DEFAULT NULL, '
            .'reference VARCHAR(128) DEFAULT NULL, '
            .'date_echeance DATE DEFAULT NULL, '
            .'prochaine_relance_cible VARCHAR(10) DEFAULT NULL, '
            .'prochaine_relance_date DATE DEFAULT NULL, '
            .'retour_id INT DEFAULT NULL, '
            .'cree_par VARCHAR(150) DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            .'modifie_par VARCHAR(150) DEFAULT NULL, '
            .'modifie_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_facture_site_ecriture ON recouvrement.facture_site (ecriture_id)');
        $this->addSql('CREATE INDEX idx_facture_site_compte ON recouvrement.facture_site (compte_code)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE recouvrement.facture_site');
    }
}
