<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527093301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shared.user_presence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_ping_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BEA912ADA76ED395 ON shared.user_presence (user_id)');
        $this->addSql('ALTER TABLE shared.user_presence ADD CONSTRAINT FK_BEA912ADA76ED395 FOREIGN KEY (user_id) REFERENCES shared.users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE shared.user_presence DROP CONSTRAINT FK_BEA912ADA76ED395');
        $this->addSql('DROP TABLE shared.user_presence');
    }
}
