<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Referentiel PARTAGE des etablissements SYNTHAUTO (schema shared) : tous les modules s'y
 * referent. `etablissement` (code, libelle, societe) + `etablissement_contact`
 * (e-mails directeur/secretaires, avec audit) pour les « relances site » du
 * recouvrement. Voir docs/RECOUVREMENT_RELANCE_SITE.md.
 *
 * Le schema `shared` existe deja (shared.users, shared.notification...).
 */
final class Version20260806120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Shared : referentiel etablissements partage (etablissement + etablissement_contact)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE shared.etablissement ('
            .'code_etab VARCHAR(8) NOT NULL, '
            .'libelle VARCHAR(150) NOT NULL, '
            .'code_societe VARCHAR(40) DEFAULT NULL, '
            .'societe VARCHAR(150) DEFAULT NULL, '
            .'actif BOOLEAN NOT NULL, '
            .'cree_le TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'PRIMARY KEY (code_etab))',
        );

        $this->addSql(
            'CREATE TABLE shared.etablissement_contact ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'etablissement_code VARCHAR(8) NOT NULL, '
            .'email VARCHAR(180) NOT NULL, '
            .'role VARCHAR(16) NOT NULL, '
            .'actif BOOLEAN NOT NULL, '
            .'cree_par VARCHAR(150) DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            .'modifie_par VARCHAR(150) DEFAULT NULL, '
            .'modifie_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_etab_contact_etab ON shared.etablissement_contact (etablissement_code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_etab_contact_email ON shared.etablissement_contact (etablissement_code, email)');
        $this->addSql(
            'ALTER TABLE shared.etablissement_contact '
            .'ADD CONSTRAINT fk_etab_contact FOREIGN KEY (etablissement_code) '
            .'REFERENCES shared.etablissement (code_etab) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE shared.etablissement_contact');
        $this->addSql('DROP TABLE shared.etablissement');
    }
}
