<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Module Recouvrement — campagnes et reporting programmable.
 *
 * Une `campagne` est une operation en lot reutilisable : selection
 * dynamique de comptes (filtres serialises en JSON), traitement
 * (modele_courrier) et planification (frequence cron-like). Chaque
 * execution est journalisee dans `campagne_execution`.
 *
 * `envoi_programme` est utilise pour les rapports recurrents (envoi
 * automatique d'un PDF/Excel a une liste de destinataires) — la
 * configuration est stockee en JSON, l'execution sera declenchee par un
 * cron Symfony Scheduler (PHASE 11).
 */
final class Version20260528201857 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recouvrement : tables campagne, campagne_execution et envoi_programme';
    }

    public function up(Schema $schema): void
    {
        // ----- creances.campagne ------------------------------------------
        $this->addSql(
            'CREATE TABLE creances.campagne ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'libelle VARCHAR(255) NOT NULL, '
            .'description TEXT DEFAULT NULL, '
            // Filtres serialises (tranches, etablissement, marque, etc.).
            .'selection JSONB NOT NULL DEFAULT \'{}\'::jsonb, '
            .'modele_courrier_id BIGINT DEFAULT NULL, '
            .'strategie_niveau_id BIGINT DEFAULT NULL, '
            // Frequence : ponctuelle, quotidienne, hebdomadaire, mensuelle
            .'frequence VARCHAR(20) NOT NULL DEFAULT \'ponctuelle\', '
            // Parametres de planification (jour, heure, etc.) en JSON libre.
            .'planification JSONB NOT NULL DEFAULT \'{}\'::jsonb, '
            .'active BOOLEAN NOT NULL DEFAULT TRUE, '
            .'prochaine_execution TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'derniere_execution TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'auteur_id INT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_camp_active ON creances.campagne (active)');
        $this->addSql('CREATE INDEX idx_creances_camp_prochaine ON creances.campagne (prochaine_execution)');
        $this->addSql(
            'ALTER TABLE creances.campagne ADD CONSTRAINT fk_creances_camp_modele '
            .'FOREIGN KEY (modele_courrier_id) REFERENCES creances.modele_courrier (id) ON DELETE SET NULL',
        );
        $this->addSql(
            'ALTER TABLE creances.campagne ADD CONSTRAINT fk_creances_camp_niveau '
            .'FOREIGN KEY (strategie_niveau_id) REFERENCES creances.strategie_niveau (id) ON DELETE SET NULL',
        );
        $this->addSql(
            'ALTER TABLE creances.campagne ADD CONSTRAINT fk_creances_camp_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // ----- creances.campagne_execution --------------------------------
        $this->addSql(
            'CREATE TABLE creances.campagne_execution ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'campagne_id BIGINT NOT NULL, '
            // statut : a_traiter, en_cours, archive, erreur
            .'statut VARCHAR(20) NOT NULL DEFAULT \'a_traiter\', '
            .'nb_comptes INT NOT NULL DEFAULT 0, '
            .'nb_envoyes INT NOT NULL DEFAULT 0, '
            .'nb_erreurs INT NOT NULL DEFAULT 0, '
            .'erreur_message TEXT DEFAULT NULL, '
            .'lance_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'archive_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'auteur_id INT DEFAULT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_cexec_camp ON creances.campagne_execution (campagne_id)');
        $this->addSql('CREATE INDEX idx_creances_cexec_statut ON creances.campagne_execution (statut)');
        $this->addSql(
            'ALTER TABLE creances.campagne_execution ADD CONSTRAINT fk_creances_cexec_camp '
            .'FOREIGN KEY (campagne_id) REFERENCES creances.campagne (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE creances.campagne_execution ADD CONSTRAINT fk_creances_cexec_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // ----- creances.envoi_programme (PHASE 11 ; cree maintenant pour
        //       eviter une migration supplementaire). Sert au reporting
        //       recurrent.
        $this->addSql(
            'CREATE TABLE creances.envoi_programme ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'libelle VARCHAR(255) NOT NULL, '
            // type : balance_agee, top10, dso, indicateurs_globaux, custom
            .'type VARCHAR(30) NOT NULL, '
            // Filtres + dimensions du rapport.
            .'configuration JSONB NOT NULL DEFAULT \'{}\'::jsonb, '
            // Frequence : quotidien, hebdomadaire, mensuel, trimestriel
            .'frequence VARCHAR(20) NOT NULL, '
            // Heure d\'envoi (HH:MM) + jour ([0-6] pour hebdo ou [1-31] pour mensuel).
            .'planification JSONB NOT NULL DEFAULT \'{}\'::jsonb, '
            // Liste d\'emails destinataires.
            .'destinataires JSONB NOT NULL DEFAULT \'[]\'::jsonb, '
            .'active BOOLEAN NOT NULL DEFAULT TRUE, '
            .'prochaine_execution TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'derniere_execution TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'auteur_id INT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_ep_active ON creances.envoi_programme (active)');
        $this->addSql('CREATE INDEX idx_creances_ep_prochaine ON creances.envoi_programme (prochaine_execution)');
        $this->addSql(
            'ALTER TABLE creances.envoi_programme ADD CONSTRAINT fk_creances_ep_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE creances.envoi_programme');
        $this->addSql('DROP TABLE creances.campagne_execution');
        $this->addSql('DROP TABLE creances.campagne');
    }
}
