<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Module Recouvrement — emails de reponse (retours client) + cache du score
 * IA enrichi.
 *
 * `email_reponse` journalise les reponses recues a une relance (par e-mail,
 * sms, courrier postal, etc.). Sources possibles :
 *  - manuel        : le comptable saisit la reponse a la main depuis la
 *                    fiche tiers ou la page dediee
 *  - webhook       : un service mail (Mailgun/SES) poste sur un endpoint
 *                    public en V2 (necessite config Tiffany)
 *  - imap          : sync directe via IMAP/Graph (V2, necessite Tiffany)
 *
 * `score_ia` cache les scores enrichis par une IA (analyse de comportement,
 * profil de paiement). Le scoring deterministe reste calcule a la volee
 * par IndicateursService ; ce cache stocke uniquement l'enrichissement IA
 * (score + commentaire en langage naturel + facteurs identifies).
 */
final class Version20260528221911 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recouvrement : tables email_reponse (retours client) et score_ia (cache scoring enrichi)';
    }

    public function up(Schema $schema): void
    {
        // ----- creances.email_reponse -------------------------------------
        $this->addSql(
            'CREATE TABLE creances.email_reponse ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            // Envoi original (peut etre null si reponse spontanee).
            .'relance_envoi_id BIGINT DEFAULT NULL, '
            .'compte_code VARCHAR(50) NOT NULL, '
            .'ecriture_numero VARCHAR(50) DEFAULT NULL, '
            .'sujet VARCHAR(255) DEFAULT NULL, '
            .'expediteur VARCHAR(255) DEFAULT NULL, '
            .'corps_texte TEXT DEFAULT NULL, '
            .'corps_html TEXT DEFAULT NULL, '
            // source : manuel, webhook, imap, graph
            .'source VARCHAR(20) NOT NULL DEFAULT \'manuel\', '
            // categorie estimee : promesse, refus, contestation, autre
            .'categorie VARCHAR(20) DEFAULT NULL, '
            .'recu_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'traite BOOLEAN NOT NULL DEFAULT FALSE, '
            .'traite_par_id INT DEFAULT NULL, '
            .'traite_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'commentaire_traitement TEXT DEFAULT NULL, '
            // Payload brut (headers + raw) pour audit / debug.
            .'payload JSONB DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_er_compte ON creances.email_reponse (compte_code)');
        $this->addSql('CREATE INDEX idx_creances_er_ecriture ON creances.email_reponse (ecriture_numero)');
        $this->addSql('CREATE INDEX idx_creances_er_envoi ON creances.email_reponse (relance_envoi_id)');
        $this->addSql('CREATE INDEX idx_creances_er_traite ON creances.email_reponse (traite)');
        $this->addSql('CREATE INDEX idx_creances_er_recu ON creances.email_reponse (recu_le)');
        $this->addSql(
            'ALTER TABLE creances.email_reponse ADD CONSTRAINT fk_creances_er_envoi '
            .'FOREIGN KEY (relance_envoi_id) REFERENCES creances.relance_envoi (id) ON DELETE SET NULL',
        );
        $this->addSql(
            'ALTER TABLE creances.email_reponse ADD CONSTRAINT fk_creances_er_traite '
            .'FOREIGN KEY (traite_par_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // ----- creances.score_ia ------------------------------------------
        $this->addSql(
            'CREATE TABLE creances.score_ia ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'compte_code VARCHAR(50) NOT NULL, '
            // Score IA enrichi (0-10), peut differer du score deterministe.
            .'score NUMERIC(3, 1) NOT NULL, '
            // Niveau de confiance de l\'IA (0-1).
            .'confiance NUMERIC(3, 2) DEFAULT NULL, '
            // Commentaire en langage naturel resumant l\'analyse.
            .'commentaire TEXT DEFAULT NULL, '
            // Facteurs identifies (liste JSON) : ex. ["promesses_repetees_non_tenues", "retards_chroniques", "litige_actif"]
            .'facteurs JSONB DEFAULT NULL, '
            // Provider utilise : anthropic, openai, algorithme, manuel
            .'provider VARCHAR(20) NOT NULL DEFAULT \'anthropic\', '
            // Modele appele : claude-haiku-4-5, gpt-4o-mini, etc.
            .'modele VARCHAR(50) DEFAULT NULL, '
            .'tokens_utilises INT DEFAULT NULL, '
            .'calcule_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'expire_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_creances_score_ia_compte ON creances.score_ia (compte_code)');
        $this->addSql('CREATE INDEX idx_creances_score_ia_calcule ON creances.score_ia (calcule_le)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE creances.score_ia');
        $this->addSql('DROP TABLE creances.email_reponse');
    }
}
