<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527081104 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shared.demande_acces (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(20) NOT NULL, roles_attribues JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, demandeur_id INT NOT NULL, decideur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1179893195A6EE59 ON shared.demande_acces (demandeur_id)');
        $this->addSql('CREATE INDEX IDX_1179893158CA7006 ON shared.demande_acces (decideur_id)');
        $this->addSql('ALTER TABLE shared.demande_acces ADD CONSTRAINT FK_1179893195A6EE59 FOREIGN KEY (demandeur_id) REFERENCES shared.users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shared.demande_acces ADD CONSTRAINT FK_1179893158CA7006 FOREIGN KEY (decideur_id) REFERENCES shared.users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE shared.demande_acces DROP CONSTRAINT FK_1179893195A6EE59');
        $this->addSql('ALTER TABLE shared.demande_acces DROP CONSTRAINT FK_1179893158CA7006');
        $this->addSql('DROP TABLE shared.demande_acces');
    }
}
