<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Module Garanties : table de scrap des dossiers de garantie constructeur
 * (sortie du RPA, copie fidele JSONB facon mirror) + historique des
 * changements de statut. Voir docs/ARCHITECTURE.md.
 *
 * Le rapprochement avec Sage (mirror.bal_eloficash) se fait a la volee sur
 * right(numvin, 8) = chassis : pas de table de jointure figee.
 */
final class Version20260527134042 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Garanties : tables dossier (scrap constructeur) et dossier_changement (historique statuts)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE garanties.dossier ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            // Cle naturelle stable = concession|num_dg|chassis|numero_or. Ne
            // contient aucun champ mutable (statut, montant) : un changement de
            // statut est un UPDATE, pas une nouvelle ligne.
            .'cle VARCHAR(255) NOT NULL, '
            .'concession VARCHAR(255) NOT NULL, '
            .'marque VARCHAR(100) DEFAULT NULL, '
            .'chassis VARCHAR(32) DEFAULT NULL, '
            .'num_dg VARCHAR(50) DEFAULT NULL, '
            .'mvs VARCHAR(50) DEFAULT NULL, '
            .'numero_or VARCHAR(50) DEFAULT NULL, '
            .'statut_code VARCHAR(10) DEFAULT NULL, '
            .'montant_dg NUMERIC(12, 2) DEFAULT NULL, '
            .'date_emission VARCHAR(6) DEFAULT NULL, '
            .'date_intervention DATE DEFAULT NULL, '
            .'date_comptable DATE DEFAULT NULL, '
            .'code_frais VARCHAR(255) DEFAULT NULL, '
            // Ligne brute du scrap, integrale : robuste si le format change.
            .'donnees JSONB NOT NULL, '
            .'content_hash VARCHAR(32) NOT NULL, '
            .'premiere_vue TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'derniere_maj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'importe_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_dossier_cle ON garanties.dossier (cle)');
        $this->addSql('CREATE INDEX idx_dossier_chassis ON garanties.dossier (chassis)');
        $this->addSql('CREATE INDEX idx_dossier_statut ON garanties.dossier (statut_code)');
        $this->addSql('CREATE INDEX idx_dossier_marque ON garanties.dossier (marque)');

        $this->addSql(
            'CREATE TABLE garanties.dossier_changement ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'dossier_id BIGINT NOT NULL, '
            .'constate_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'ancien_statut VARCHAR(10) DEFAULT NULL, '
            .'nouveau_statut VARCHAR(10) DEFAULT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_changement_dossier ON garanties.dossier_changement (dossier_id)');
        $this->addSql(
            'ALTER TABLE garanties.dossier_changement '
            .'ADD CONSTRAINT fk_changement_dossier FOREIGN KEY (dossier_id) '
            .'REFERENCES garanties.dossier (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE garanties.dossier_changement');
        $this->addSql('DROP TABLE garanties.dossier');
    }
}
