<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Module Recouvrement — modeles de courrier (HTML/email) et journal des
 * envois de relance.
 *
 * `modele_courrier` est utilise par les strategies de relance et par les
 * envois ponctuels. Le format de sortie principal est l'email avec corps
 * HTML rendu via Twig ; le PDF arrivera quand l'ajout de dompdf/mpdf sera
 * valide (hors perimetre du module : composer.json).
 *
 * `relance_envoi` est le journal de chaque envoi (unique ou en lot) : on
 * y stocke le destinataire, le sujet, le corps HTML rendu, le statut et
 * eventuellement le message d'erreur SMTP. Sert aussi pour le reporting et
 * la verification "qui a recu quoi".
 */
final class Version20260528192331 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recouvrement : tables modele_courrier et relance_envoi (journal des envois)';
    }

    public function up(Schema $schema): void
    {
        // ----- creances.modele_courrier ----------------------------------
        $this->addSql(
            'CREATE TABLE creances.modele_courrier ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'code VARCHAR(50) NOT NULL, '
            .'libelle VARCHAR(255) NOT NULL, '
            .'description TEXT DEFAULT NULL, '
            // Format de sortie principal : email (corps HTML) ou courrier
            // (corps HTML imprimable en attendant le PDF). Pas d'enum SQL
            // pour rester souple.
            .'format VARCHAR(20) NOT NULL DEFAULT \'email\', '
            .'langue VARCHAR(5) NOT NULL DEFAULT \'fr\', '
            // Sujet (pour email). Variables Twig autorisees.
            .'sujet VARCHAR(255) DEFAULT NULL, '
            // Corps HTML, supporte les variables Twig (compte, tiers,
            // ecritures, montant_total, lien_portail, etc.).
            .'corps_html TEXT NOT NULL, '
            .'actif BOOLEAN NOT NULL DEFAULT TRUE, '
            .'auteur_id INT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_creances_mc_code ON creances.modele_courrier (code)');
        $this->addSql('CREATE INDEX idx_creances_mc_actif ON creances.modele_courrier (actif)');
        $this->addSql('CREATE INDEX idx_creances_mc_format ON creances.modele_courrier (format)');
        $this->addSql(
            'ALTER TABLE creances.modele_courrier ADD CONSTRAINT fk_creances_mc_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // Rattacher (a posteriori) strategie_niveau.modele_courrier_id a
        // creances.modele_courrier maintenant que la table existe.
        $this->addSql(
            'ALTER TABLE creances.strategie_niveau ADD CONSTRAINT fk_creances_sn_modele '
            .'FOREIGN KEY (modele_courrier_id) REFERENCES creances.modele_courrier (id) ON DELETE SET NULL',
        );

        // ----- creances.relance_envoi ------------------------------------
        $this->addSql(
            'CREATE TABLE creances.relance_envoi ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'compte_code VARCHAR(50) NOT NULL, '
            .'ecriture_numero VARCHAR(50) DEFAULT NULL, '
            // Niveau de strategie applique (null si envoi manuel hors
            // strategie).
            .'strategie_niveau_id BIGINT DEFAULT NULL, '
            .'modele_courrier_id BIGINT DEFAULT NULL, '
            // Vecteur : email, courrier, extraction, sms.
            .'vecteur VARCHAR(20) NOT NULL, '
            .'destinataire VARCHAR(255) DEFAULT NULL, '
            .'sujet VARCHAR(255) DEFAULT NULL, '
            // Corps rendu (template + variables resolues). Pour audit.
            .'corps_html TEXT DEFAULT NULL, '
            // Statut : a_envoyer, envoye, erreur, supprime, archive
            .'statut VARCHAR(20) NOT NULL DEFAULT \'a_envoyer\', '
            .'erreur_message TEXT DEFAULT NULL, '
            // Chemin d'un eventuel fichier (PDF a venir).
            .'fichier_path VARCHAR(500) DEFAULT NULL, '
            .'envoye_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'archive_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'auteur_id INT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_re_compte ON creances.relance_envoi (compte_code)');
        $this->addSql('CREATE INDEX idx_creances_re_ecriture ON creances.relance_envoi (ecriture_numero)');
        $this->addSql('CREATE INDEX idx_creances_re_statut ON creances.relance_envoi (statut)');
        $this->addSql('CREATE INDEX idx_creances_re_envoye ON creances.relance_envoi (envoye_le)');
        $this->addSql('CREATE INDEX idx_creances_re_niveau ON creances.relance_envoi (strategie_niveau_id)');
        $this->addSql(
            'ALTER TABLE creances.relance_envoi ADD CONSTRAINT fk_creances_re_niveau '
            .'FOREIGN KEY (strategie_niveau_id) REFERENCES creances.strategie_niveau (id) ON DELETE SET NULL',
        );
        $this->addSql(
            'ALTER TABLE creances.relance_envoi ADD CONSTRAINT fk_creances_re_modele '
            .'FOREIGN KEY (modele_courrier_id) REFERENCES creances.modele_courrier (id) ON DELETE SET NULL',
        );
        $this->addSql(
            'ALTER TABLE creances.relance_envoi ADD CONSTRAINT fk_creances_re_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE creances.relance_envoi');
        $this->addSql('ALTER TABLE creances.strategie_niveau DROP CONSTRAINT fk_creances_sn_modele');
        $this->addSql('DROP TABLE creances.modele_courrier');
    }
}
