<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Annotations libres sur un dossier de garantie : note + auteur + horodatage.
 *
 * Volontairement minimal pour le V1 : pas de statut interne ni de date de
 * prochaine action (a affiner avec le retour de l'auditeur). Voir docs/ARCHITECTURE.md.
 */
final class Version20260528083407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Garanties : table note (annotations auditeur sur un dossier)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE garanties.note ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'dossier_id BIGINT NOT NULL, '
            .'auteur_id INT NOT NULL, '
            .'texte TEXT NOT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_note_dossier ON garanties.note (dossier_id)');
        $this->addSql('CREATE INDEX idx_note_auteur ON garanties.note (auteur_id)');
        $this->addSql(
            'ALTER TABLE garanties.note '
            .'ADD CONSTRAINT fk_note_dossier FOREIGN KEY (dossier_id) '
            .'REFERENCES garanties.dossier (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE garanties.note '
            .'ADD CONSTRAINT fk_note_auteur FOREIGN KEY (auteur_id) '
            .'REFERENCES shared.users (id) ON DELETE RESTRICT',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE garanties.note');
    }
}
