<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Module Remboursement client — socle (Lot 1). Cree le schema `remboursement`
 * et ses tables de base : dossier (agregat + machine a etats), dossier_piece
 * (pieces stockees par l'app), dossier_transition (journal d'audit inviolable).
 * Voir docs/MODULE_REMBOURSEMENT.md.
 *
 * NON appliquee automatiquement : additive et isolee (nouveau schema), sans
 * impact sur les schemas existants.
 */
final class Version20260811120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remboursement : schema + dossier / dossier_piece / dossier_transition (socle)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA IF NOT EXISTS remboursement');

        $this->addSql(
            'CREATE TABLE remboursement.dossier ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'reference VARCHAR(32) NOT NULL, '
            .'motif VARCHAR(16) NOT NULL, '
            .'statut VARCHAR(24) NOT NULL, '
            .'etablissement_code VARCHAR(8) DEFAULT NULL, '
            .'nom_client VARCHAR(180) NOT NULL, '
            .'iban_client TEXT DEFAULT NULL, '
            .'bic_client TEXT DEFAULT NULL, '
            .'immatriculation VARCHAR(32) DEFAULT NULL, '
            .'code_icar VARCHAR(32) DEFAULT NULL, '
            .'montant NUMERIC(14, 2) NOT NULL, '
            .'controle_nom VARCHAR(180) DEFAULT NULL, '
            .'controle_iban TEXT DEFAULT NULL, '
            .'controle_bic TEXT DEFAULT NULL, '
            .'controle_montant NUMERIC(14, 2) DEFAULT NULL, '
            .'controle_immatriculation VARCHAR(32) DEFAULT NULL, '
            .'controle_icar VARCHAR(32) DEFAULT NULL, '
            .'controle_extra JSON DEFAULT NULL, '
            .'verdict_ia VARCHAR(16) DEFAULT NULL, '
            .'verdict_info TEXT DEFAULT NULL, '
            .'cle_doublon VARCHAR(64) DEFAULT NULL, '
            .'refus_motif TEXT DEFAULT NULL, '
            .'cree_par VARCHAR(150) DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            .'modifie_par VARCHAR(150) DEFAULT NULL, '
            .'modifie_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'depose_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'valide_directeur_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'confirme_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'paye_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_remb_dossier_reference ON remboursement.dossier (reference)');
        $this->addSql('CREATE INDEX idx_remb_dossier_statut ON remboursement.dossier (statut)');
        $this->addSql('CREATE INDEX idx_remb_dossier_cle_doublon ON remboursement.dossier (motif, cle_doublon)');
        $this->addSql('CREATE INDEX idx_remb_dossier_etab ON remboursement.dossier (etablissement_code)');

        $this->addSql(
            'CREATE TABLE remboursement.dossier_piece ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'dossier_id BIGINT NOT NULL, '
            .'type VARCHAR(32) NOT NULL, '
            .'nom_fichier VARCHAR(255) NOT NULL, '
            .'chemin_stockage VARCHAR(512) NOT NULL, '
            .'mime_type VARCHAR(100) NOT NULL, '
            .'taille_octets INT NOT NULL, '
            .'hash VARCHAR(64) DEFAULT NULL, '
            .'uploade_par VARCHAR(150) DEFAULT NULL, '
            .'uploade_le TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_remb_piece_dossier ON remboursement.dossier_piece (dossier_id)');
        $this->addSql(
            'ALTER TABLE remboursement.dossier_piece ADD CONSTRAINT fk_remb_piece_dossier '
            .'FOREIGN KEY (dossier_id) REFERENCES remboursement.dossier (id) ON DELETE CASCADE',
        );

        $this->addSql(
            'CREATE TABLE remboursement.dossier_transition ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'dossier_id BIGINT NOT NULL, '
            .'de_statut VARCHAR(24) DEFAULT NULL, '
            .'vers_statut VARCHAR(24) NOT NULL, '
            .'transition VARCHAR(64) NOT NULL, '
            .'par VARCHAR(150) DEFAULT NULL, '
            .'le TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            .'commentaire TEXT DEFAULT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_remb_transition_dossier ON remboursement.dossier_transition (dossier_id)');
        $this->addSql(
            'ALTER TABLE remboursement.dossier_transition ADD CONSTRAINT fk_remb_transition_dossier '
            .'FOREIGN KEY (dossier_id) REFERENCES remboursement.dossier (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS remboursement.dossier_transition');
        $this->addSql('DROP TABLE IF EXISTS remboursement.dossier_piece');
        $this->addSql('DROP TABLE IF EXISTS remboursement.dossier');
        $this->addSql('DROP SCHEMA IF EXISTS remboursement');
    }
}
