<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Module Recouvrement (creances) — fondations metier.
 *
 * Cree dans le schema `creances` les six tables qui portent l'activite de
 * recouvrement au-dessus du mirror Sage (lecture seule) :
 *
 *   - note               : annotations libres (compte ou ecriture)
 *   - action             : actions/relances avec echeance, destinataire et resultat
 *   - promesse           : promesses simples de paiement par ecriture
 *   - dossier            : dossier metier (litige / contentieux / echeancier)
 *   - dossier_ecriture   : pivot dossier ↔ ecritures (avec montant partiel)
 *   - echeance           : echeances d'un dossier de type echeancier
 *
 * Les ecritures et les tiers ne sont pas FK : ils vivent dans `mirror.*` et
 * sont referencees via leur identifiant Sage (compte_code, ecriture_numero).
 * Les FK pointent uniquement vers shared.users (auteur / destinataire /
 * responsable). Tous les ON DELETE des FK utilisateur sont SET NULL pour
 * conserver l'historique meme apres depart d'un comptable.
 */
final class Version20260528144141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recouvrement : tables fondations (note, action, promesse, dossier, dossier_ecriture, echeance)';
    }

    public function up(Schema $schema): void
    {
        // ----- creances.note ---------------------------------------------
        // Annotation libre, attachee a un compte (compte_code) et
        // optionnellement a une ecriture (ecriture_numero).
        $this->addSql(
            'CREATE TABLE creances.note ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'compte_code VARCHAR(50) NOT NULL, '
            .'ecriture_numero VARCHAR(50) DEFAULT NULL, '
            .'contenu TEXT NOT NULL, '
            .'auteur_id INT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_note_compte ON creances.note (compte_code)');
        $this->addSql('CREATE INDEX idx_creances_note_ecriture ON creances.note (ecriture_numero)');
        $this->addSql('CREATE INDEX idx_creances_note_auteur ON creances.note (auteur_id)');
        $this->addSql(
            'ALTER TABLE creances.note ADD CONSTRAINT fk_creances_note_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // ----- creances.action -------------------------------------------
        // Une action = un point de contact a faire ou deja effectue
        // (telephone, e-mail manuel, courrier, sms, visite). Peut etre liee
        // a une ecriture precise ou rester au niveau du compte.
        $this->addSql(
            'CREATE TABLE creances.action ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'compte_code VARCHAR(50) NOT NULL, '
            .'ecriture_numero VARCHAR(50) DEFAULT NULL, '
            // type : telephone, email, courrier, sms, visite, autre
            .'type VARCHAR(30) NOT NULL, '
            .'libelle VARCHAR(255) NOT NULL, '
            .'description TEXT DEFAULT NULL, '
            .'echeance DATE NOT NULL, '
            .'realisee BOOLEAN NOT NULL DEFAULT FALSE, '
            // resultat : contact_ok, contact_ko, promesse, refus, autre
            .'resultat VARCHAR(30) DEFAULT NULL, '
            .'commentaire_resultat TEXT DEFAULT NULL, '
            .'auteur_id INT DEFAULT NULL, '
            .'destinataire_id INT DEFAULT NULL, '
            .'realisee_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_action_compte ON creances.action (compte_code)');
        $this->addSql('CREATE INDEX idx_creances_action_ecriture ON creances.action (ecriture_numero)');
        $this->addSql('CREATE INDEX idx_creances_action_echeance ON creances.action (echeance)');
        $this->addSql('CREATE INDEX idx_creances_action_destinataire ON creances.action (destinataire_id)');
        $this->addSql('CREATE INDEX idx_creances_action_realisee ON creances.action (realisee)');
        $this->addSql(
            'ALTER TABLE creances.action ADD CONSTRAINT fk_creances_action_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );
        $this->addSql(
            'ALTER TABLE creances.action ADD CONSTRAINT fk_creances_action_dest '
            .'FOREIGN KEY (destinataire_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // ----- creances.promesse -----------------------------------------
        // Promesse de paiement simple sur une ecriture. Pour un echeancier
        // complet, utiliser un dossier de type "echeancier" + table echeance.
        $this->addSql(
            'CREATE TABLE creances.promesse ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'compte_code VARCHAR(50) NOT NULL, '
            .'ecriture_numero VARCHAR(50) NOT NULL, '
            .'date_promesse DATE NOT NULL, '
            // Montant null = la totalite du solde de l'ecriture.
            .'montant NUMERIC(12, 2) DEFAULT NULL, '
            .'commentaire TEXT DEFAULT NULL, '
            // statut : en_cours, tenue, non_tenue, annulee
            .'statut VARCHAR(20) NOT NULL DEFAULT \'en_cours\', '
            .'auteur_id INT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_promesse_compte ON creances.promesse (compte_code)');
        $this->addSql('CREATE INDEX idx_creances_promesse_ecriture ON creances.promesse (ecriture_numero)');
        $this->addSql('CREATE INDEX idx_creances_promesse_date ON creances.promesse (date_promesse)');
        $this->addSql('CREATE INDEX idx_creances_promesse_statut ON creances.promesse (statut)');
        $this->addSql(
            'ALTER TABLE creances.promesse ADD CONSTRAINT fk_creances_promesse_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // ----- creances.dossier ------------------------------------------
        // Conteneur metier qui regroupe des ecritures et historise une
        // action longue : echeancier de paiement, litige, contentieux.
        $this->addSql(
            'CREATE TABLE creances.dossier ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'compte_code VARCHAR(50) NOT NULL, '
            // type : echeancier, litige, contentieux
            .'type VARCHAR(20) NOT NULL, '
            .'libelle VARCHAR(255) NOT NULL, '
            .'description TEXT DEFAULT NULL, '
            .'responsable_id INT DEFAULT NULL, '
            .'date_debut DATE NOT NULL, '
            .'date_resolution_cible DATE DEFAULT NULL, '
            .'date_resolution DATE DEFAULT NULL, '
            .'resultat VARCHAR(50) DEFAULT NULL, '
            .'commentaire_resolution TEXT DEFAULT NULL, '
            // statut : ouvert, clos
            .'statut VARCHAR(20) NOT NULL DEFAULT \'ouvert\', '
            // Snapshot du montant total a la creation (somme des ecritures).
            // Mis a jour lors de l'ajout/retrait d'ecritures.
            .'montant_total NUMERIC(14, 2) DEFAULT NULL, '
            .'auteur_id INT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_dossier_compte ON creances.dossier (compte_code)');
        $this->addSql('CREATE INDEX idx_creances_dossier_type ON creances.dossier (type)');
        $this->addSql('CREATE INDEX idx_creances_dossier_statut ON creances.dossier (statut)');
        $this->addSql('CREATE INDEX idx_creances_dossier_responsable ON creances.dossier (responsable_id)');
        $this->addSql('CREATE INDEX idx_creances_dossier_date_debut ON creances.dossier (date_debut)');
        $this->addSql(
            'ALTER TABLE creances.dossier ADD CONSTRAINT fk_creances_dossier_responsable '
            .'FOREIGN KEY (responsable_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );
        $this->addSql(
            'ALTER TABLE creances.dossier ADD CONSTRAINT fk_creances_dossier_auteur '
            .'FOREIGN KEY (auteur_id) REFERENCES shared.users (id) ON DELETE SET NULL',
        );

        // ----- creances.dossier_ecriture ---------------------------------
        // Pivot dossier <-> ecritures Sage. Pour un litige, on peut affecter
        // un montant partiel (le client conteste 200 EUR sur une facture de
        // 1000 EUR par exemple) et resoudre par ecriture.
        $this->addSql(
            'CREATE TABLE creances.dossier_ecriture ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'dossier_id BIGINT NOT NULL, '
            .'ecriture_numero VARCHAR(50) NOT NULL, '
            .'montant_partiel NUMERIC(12, 2) DEFAULT NULL, '
            .'date_resolution DATE DEFAULT NULL, '
            .'commentaire TEXT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_de_dossier ON creances.dossier_ecriture (dossier_id)');
        $this->addSql('CREATE INDEX idx_creances_de_ecriture ON creances.dossier_ecriture (ecriture_numero)');
        $this->addSql('CREATE UNIQUE INDEX uniq_creances_de_dossier_ecriture ON creances.dossier_ecriture (dossier_id, ecriture_numero)');
        $this->addSql(
            'ALTER TABLE creances.dossier_ecriture ADD CONSTRAINT fk_creances_de_dossier '
            .'FOREIGN KEY (dossier_id) REFERENCES creances.dossier (id) ON DELETE CASCADE',
        );

        // ----- creances.echeance -----------------------------------------
        // Echeance d'un dossier de type "echeancier" (plan de paiement
        // negocie avec le client).
        $this->addSql(
            'CREATE TABLE creances.echeance ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'dossier_id BIGINT NOT NULL, '
            .'numero INT NOT NULL, '
            .'date_prevue DATE NOT NULL, '
            .'montant NUMERIC(12, 2) NOT NULL, '
            .'montant_regle NUMERIC(12, 2) NOT NULL DEFAULT 0, '
            .'date_reglement DATE DEFAULT NULL, '
            // statut : a_venir, partiel, regle, en_retard
            .'statut VARCHAR(20) NOT NULL DEFAULT \'a_venir\', '
            .'commentaire TEXT DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'modifie_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_creances_echeance_dossier ON creances.echeance (dossier_id)');
        $this->addSql('CREATE INDEX idx_creances_echeance_date ON creances.echeance (date_prevue)');
        $this->addSql('CREATE INDEX idx_creances_echeance_statut ON creances.echeance (statut)');
        $this->addSql(
            'ALTER TABLE creances.echeance ADD CONSTRAINT fk_creances_echeance_dossier '
            .'FOREIGN KEY (dossier_id) REFERENCES creances.dossier (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE creances.echeance');
        $this->addSql('DROP TABLE creances.dossier_ecriture');
        $this->addSql('DROP TABLE creances.dossier');
        $this->addSql('DROP TABLE creances.promesse');
        $this->addSql('DROP TABLE creances.action');
        $this->addSql('DROP TABLE creances.note');
    }
}
