<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Recouvrement : dossier de « relance au site » (Phase 2). Table
 * recouvrement.demande_site (un dossier par compte+site : cadence, token de la page
 * de réponse, destinataires, fil) + rattachement des factures via
 * recouvrement.facture_site.demande_site_id. Voir docs/RECOUVREMENT_RELANCE_SITE.md.
 */
final class Version20260806140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recouvrement : table demande_site + facture_site.demande_site_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE recouvrement.demande_site ('
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'compte_code VARCHAR(64) NOT NULL, '
            .'code_site VARCHAR(8) NOT NULL, '
            .'statut VARCHAR(16) NOT NULL, '
            .'cadence_intervalle VARCHAR(8) NOT NULL, '
            .'token VARCHAR(64) NOT NULL, '
            .'destinataires JSON DEFAULT NULL, '
            .'message TEXT DEFAULT NULL, '
            .'dernier_envoi_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'retour_id INT DEFAULT NULL, '
            .'cree_par VARCHAR(150) DEFAULT NULL, '
            .'cree_le TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            .'modifie_par VARCHAR(150) DEFAULT NULL, '
            .'modifie_le TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_demande_site_compte_site ON recouvrement.demande_site (compte_code, code_site)');
        $this->addSql('CREATE UNIQUE INDEX uniq_demande_site_token ON recouvrement.demande_site (token)');

        $this->addSql('ALTER TABLE recouvrement.facture_site ADD COLUMN demande_site_id BIGINT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_facture_site_demande ON recouvrement.facture_site (demande_site_id)');
        $this->addSql(
            'ALTER TABLE recouvrement.facture_site '
            .'ADD CONSTRAINT fk_facture_site_demande FOREIGN KEY (demande_site_id) '
            .'REFERENCES recouvrement.demande_site (id) ON DELETE SET NULL',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE recouvrement.facture_site DROP CONSTRAINT fk_facture_site_demande');
        $this->addSql('ALTER TABLE recouvrement.facture_site DROP COLUMN demande_site_id');
        $this->addSql('DROP TABLE recouvrement.demande_site');
    }
}
